name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Jokester.sln
      Test_Project_Path: Jokester.Tests\Jokester.Tests.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install .NET Maui Workload
      run: dotnet workload install maui
    
    - name: Install Dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - name: Execute unit tests
      run: dotnet test --no-restore
